---
title: "Case Study 1"
author: "Emma Michael"
date: "`r Sys.Date()`"
output: html_document
---

# Copied and Pasted from Textbook

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Download the required packages
library(shiny)
library(vroom)
library(tidyverse)

```

```{r}

# Download the required data
dir.create("neiss")
#> Warning in dir.create("neiss"): 'neiss' already exists
download <- function(name) {
  url <- "https://raw.github.com/hadley/mastering-shiny/main/neiss/"
  download.file(paste0(url, name), 
                paste0("neiss/", name), 
                quiet = TRUE)
}
download("injuries.tsv.gz")
download("population.tsv")
download("products.tsv")

```

```{r}

injuries <- vroom::vroom(
  "neiss/injuries.tsv.gz")
injuries

```

```{r}

products <- vroom::vroom("neiss/products.tsv")
products

population <- vroom::vroom(
  "neiss/population.tsv")
population

```

```{r}

selected <- injuries %>% filter(
  prod_code == 649)
nrow(selected)

```

```{r}

selected %>% count(
  location, wt = weight, sort = TRUE)

selected %>% count(
  body_part, wt = weight, sort = TRUE)

selected %>% count(
  diag, wt = weight, sort = TRUE)

```

```{r}

summary <- selected %>% 
  count(age, sex, wt = weight)
summary

summary %>% 
  ggplot(aes(age, n, colour = sex)) + 
  geom_line() + 
  labs(y = "Estimated number of injuries")

```

```{r}

summary <- selected %>% 
  count(age, sex, wt = weight) %>% 
  left_join(
    population, by = c("age", "sex")) %>% 
  mutate(rate = n / population * 1e4)

summary

```

```{r}

summary %>% 
  ggplot(aes(age, rate, colour = sex)) + 
  geom_line(na.rm = TRUE) + 
  labs(y = "Injuries per 10,000 people")

```

```{r}

selected %>% 
  sample_n(10) %>% 
  pull(narrative)

```

```{r}

injuries %>%
  mutate(diag = fct_lump(fct_infreq(diag), 
                         n = 5)) %>%
  group_by(diag) %>%
  summarise(n = as.integer(sum(weight)))

```

```{r}

count_top <- function(df, var, n = 5) {
  df %>%
    mutate({{ var }} := fct_lump(
      fct_infreq({{ var }}), n = n)) %>%
    group_by({{ var }}) %>%
    summarise(n = as.integer(sum(weight)))
}

```